//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.10 at 11:53:53 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://npci.org/upi/schema/")
package org.apache.fineract.infrastructure.upi.xsd;
